# Generated by Django 4.2.7 on 2023-11-21 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaanaapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artists_name', models.CharField(max_length=100)),
                ('artists_img', models.ImageField(upload_to='pics')),
                ('artists_file', models.FileField(upload_to='songs')),
            ],
        ),
        migrations.CreateModel(
            name='Top',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_name', models.CharField(max_length=100)),
                ('top_img', models.ImageField(upload_to='pics')),
                ('top_file', models.FileField(upload_to='songs')),
            ],
        ),
        migrations.CreateModel(
            name='Trend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trend_name', models.CharField(max_length=100)),
                ('trend_img', models.ImageField(upload_to='pics')),
                ('trend_file', models.FileField(upload_to='songs')),
            ],
        ),
    ]
