# Generated by Django 4.2.7 on 2023-11-21 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gaanaapp', '0002_artist_top_trend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='artists_file',
        ),
        migrations.RemoveField(
            model_name='top',
            name='top_file',
        ),
    ]
