# Generated by Django 4.2.7 on 2023-11-21 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaanaapp', '0005_artist_artists_id_recent_recent_id_top_top_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='id',
        ),
        migrations.RemoveField(
            model_name='recent',
            name='id',
        ),
        migrations.RemoveField(
            model_name='top',
            name='id',
        ),
        migrations.RemoveField(
            model_name='trend',
            name='id',
        ),
        migrations.AlterField(
            model_name='artist',
            name='artists_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='recent',
            name='recent_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='top',
            name='top_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trend',
            name='trend_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
