# Generated by Django 4.2.7 on 2023-11-21 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaanaapp', '0006_remove_artist_id_remove_recent_id_remove_top_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='artists_id',
        ),
        migrations.RemoveField(
            model_name='recent',
            name='recent_id',
        ),
        migrations.RemoveField(
            model_name='top',
            name='top_id',
        ),
        migrations.RemoveField(
            model_name='trend',
            name='trend_id',
        ),
        migrations.AddField(
            model_name='artist',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recent',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='top',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trend',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
