# Generated by Django 4.2.7 on 2023-11-22 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gaanaapp', '0008_recent_artists_name_trend_artists_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recent',
            name='artists_name',
        ),
        migrations.RemoveField(
            model_name='trend',
            name='artists_name',
        ),
    ]
